// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJVpumiDuYMPzC5toXe0kyVMjgUKyFPZI',
    appId: '1:496350025456:web:daff5b482a865f38cf1435',
    messagingSenderId: '496350025456',
    projectId: 'likealocal-9cfde',
    authDomain: 'likealocal-9cfde.firebaseapp.com',
    storageBucket: 'likealocal-9cfde.firebasestorage.app',
    measurementId: 'G-KMZHDLY549',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_t45kiEeY1gz9q4OdOscSIxgc9c9mCZA',
    appId: '1:496350025456:android:c524350206d714cdcf1435',
    messagingSenderId: '496350025456',
    projectId: 'likealocal-9cfde',
    storageBucket: 'likealocal-9cfde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHe9j2z-WPV7FPE-TXZ_n_IaUhuISenjQ',
    appId: '1:496350025456:ios:4bb63a46b4c35a48cf1435',
    messagingSenderId: '496350025456',
    projectId: 'likealocal-9cfde',
    storageBucket: 'likealocal-9cfde.firebasestorage.app',
    iosBundleId: 'com.example.likealocal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHe9j2z-WPV7FPE-TXZ_n_IaUhuISenjQ',
    appId: '1:496350025456:ios:4bb63a46b4c35a48cf1435',
    messagingSenderId: '496350025456',
    projectId: 'likealocal-9cfde',
    storageBucket: 'likealocal-9cfde.firebasestorage.app',
    iosBundleId: 'com.example.likealocal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJVpumiDuYMPzC5toXe0kyVMjgUKyFPZI',
    appId: '1:496350025456:web:86783d7837500c6ecf1435',
    messagingSenderId: '496350025456',
    projectId: 'likealocal-9cfde',
    authDomain: 'likealocal-9cfde.firebaseapp.com',
    storageBucket: 'likealocal-9cfde.firebasestorage.app',
    measurementId: 'G-GL3DZ5KXF1',
  );
}
